name: Docker Build and Test

on:
  push:
    branches:
      - docker-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t math-function:latest .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pull and Test Docker Image
      run: |
        docker build -t math-functions:latest .
        docker run math-functions:latest